import { defineLevel } from '../../engine/defs.js';

// E1M1: CUBICLE FARM. 3:07 AM, the 13th floor. Alex steps out of the
// elevator into an office that should be empty.
//
// Route: lobby -> cubicle farm -> conference room (tack shotgun; taking it
// opens the closets) -> manager's office (blue badge) -> back through the
// break room -> blue door -> copy room -> stairwell exit.
// Secrets: the cubicle without a door (top right of the farm), the vending
// machine on the break room's south wall, and the dark panel on the east wall
// of the manager's office (rooftop balcony with the Chicago Typewriter).
export default defineLevel({
id: 'e1m1',
  mapLabel: 'E1M1',
  name: 'CUBICLE FARM',
  music: 'office',
  sky: 'sky-city',
  par: 90,
  legend: {
    x: { base: 'r', tag: 'conf' }, // conference room floor (its lights go out)
    q: { door: 'door-office', jamb: 'door-jamb', lock: 'remote', tag: 'closets' },
    u: { door: 'cubicle', secret: true },
    v: { door: 'vending', secret: true },
    y: { door: 'wood-panel-dark', secret: true },
    z: { floor: 'concrete-floor', ceiling: 'sky', light: 168, secret: true },
  },
  thingLegend: {
    Z: { type: 'imp', tag: 'closet-imps' },
    9: { type: 'imp', tag: 'closet-imps', skill: [3, 4, 5] },
  },
  tiles: [
    '                                                               ',
    ' #############B#####B######## ##### ##### wwNwNNwNNwNNwNNww    ',
    ' #,+,,,,,,,,,,,,,,,,,,,,,,,,# #...# #...# wrrrrrrrrrrrrrrrw    ',
    ' #,,,,,,,,,,,,,,,,,,,,,,,,,,# #...# #...# wrrrrrrrrrrrrrrrw    ',
    ' #,,CCCC,,c,,c,,CCCC,,PPPP,,# #...# #...# wrrrrrrrrrrrrrrrwOOOO',
    ' #,,C,,C,,c,,c,,C,,C,,P??P,,#WWWqWWBBWqWWWWrrrrrrrrrrrrrrrwzzzO',
    ' #,,C,,C,,c,,c,,C,,C,,P??P,,#xxxxxxxxxxxxxWrrrrrr:::rrrrrrwzzzO',
    ' #,,C,,C,,cccc,,C,,C,,PuPP,,#xxxxxxxxxxxxxWrrrrrr:::rrrrrrwzzzO',
    ' #,,,,,,,,,,,,,,,,,,,,,,,,,,#xxxxxxxxxxxxxWrrrrrr:::rrrrrryzzzO',
    ' #,,,;,,,,,;,,,,,;,,,,,;,,,,DxxxxxxxxxxxxxWrrrrrrrrrrrrrrrwzzzO',
    ' #,,,,,,,,,,,,,,,,,,,,,,,,,,#xxxxxxxxxxxxxWrrrrrrrrrrrrrrrwzzzO',
    ' #,,Q,,Q,,CCCC,,c,,c,,CCCC,,#xxxxxxxxxxxxxDrrrrrrrrrrrrrrrwzzzO',
    ' #,,Q,,Q,,C,,C,,c,,c,,C,,C,,#xxxxxxxxxxxxxWrrrrrrrrrrrrrrrwOOOO',
    ' #,,Q,,Q,,C,,C,,c,,c,,C,,C,,#xxxxxxxxxxxxxWrrrrrrrrrrrrrrrw    ',
    ' #,,QQQQ,,C,,C,,cccc,,C,,C,,#xxxxxxxxxxxxxWrrrrrrrrrrrrrrrw    ',
    ' #,,,,,,,,,,,,,,,,,,,,,,,,,,#xxxxxxxxxxxxxWwwwwwwwwwwwwwwww    ',
    ' #,,,,,,,,,:::,,,,,,,,,,,,,,#xxxxxxxxxxxxxW...............#    ',
    ' #,,,,,,,,,:::,,,,,,,,,,,,,,#WWWWWDWWWWWWWW...............#    ',
    ' #,,,,,,,,,:::,,,,,,,,,,,,,!#    #_#      #...............#    ',
    ' ###########D#####################_###    #...............#    ',
    '     W.............W_________________#    #...;.......;...#    ',
    '     W.............W_________________#    #...............#    ',
    '     W.............W_________________V    #...............#    ',
    '     W...:.....:...W_________________V    #...............#    ',
    '     W.............W____=_______=____V    #...............#    ',
    'EEEEEE.............W_________________#    #...............#    ',
    'EeeeeE.............W_________________#    #...............#    ',
    'EeeeeE.............W_________________######...............#    ',
    'EeeeeL.............W______________________1...............#    ',
    'EeeeeE.............W_________________######...;.......;...#    ',
    'EeeeeE.............D_________________#    #...............#    ',
    'EEEEEE.............W_________________#    #...............#    ',
    '     W...:.....:...W____=_______=____#    #...............#    ',
    '     W.............W_________________#    ########M########    ',
    '     W.............W_________________#        H-------H        ',
    '     W.............W_________________#        H-------H        ',
    '     W.............W_________________#        H-------H        ',
    '     WWWWWWWAWWWWWWW####v#############        H-------H        ',
    '                      #???#                   H-------H        ',
    '                      #???#                   H-------H        ',
    '                      #???#                   H-------H        ',
    '                      #####                   HHHHXHHHH        ',
  ],
  things: [
    '',
    '',
    '  ;                        ;',
    '         d                m    Z 9   Z 9    l;          l',
    '                                                  h   &',
    '     h      H          p                         HHH',
    '      i           h     z                                   4',
    '                                                  b',
    '                                                             U',
    '        ,     ,     @             h',
    '  ;                             hHHHH         m             S',
    '                                 HHHHh',
    '      h           i     h          h                   m',
    '           ih    H      !                   F           a',
    '                                   3',
    '                              t         F',
    '                    ,    s',
    '   m    k            k                      X  X  X      L',
    '  +                                                    m L',
    '                                                         L',
    '      F           F W',
    '                                   @              ,',
    '       ,    h    ,          m',
    '                                                i',
    '          HHHHH                              S',
    '                                                        d',
    '                 =             h                     i',
    '                         HHd  HH',
    '  >            i         h            s',
    '',
    '          s          ,              ,             ,',
    '                             d              &       !',
    '                                                        l',
    '                !     i',
    '        i                        m             Y     Y',
    '',
    '      F           W "               k               i',
    '',
    '                                                i',
    '                        a                         &',
    '                       S ,                           t',
  ],
triggers: [
    { on: 'start', do: [{ action: 'message', text: '13TH FLOOR. 3:07 AM. SOMETHING IS SCREAMING IN THE BREAK ROOM.' }] },
    {
      on: 'pickup',
      thing: 'pickup-tack-shotgun',
      do: [
        { action: 'setLight', tag: 'conf', light: 56 },
        { action: 'openDoors', tag: 'closets' },
        { action: 'message', text: 'MANDATORY TEAM-BUILDING HAS BEGUN.' },
      ],
    },
    { on: 'killed', tag: 'closet-imps', do: [{ action: 'setLight', tag: 'conf', light: 128 }] },
  ],
});
