import { defineLevel } from '../../engine/defs.js';

// E1M2: THE SERVER ROOM. Down the stairs from the 13th floor, the IT
// department hums. The racks have started blinking in patterns nobody wrote.
//
// Route: stairwell -> help desk -> server hall (Chicago Typewriter) ->
// cooling room (blue badge) -> blue door into the NOC (yellow badge; picking
// it up opens a shortcut to the corridor) -> yellow door at the bottom of the
// server hall -> freight lobby -> freight elevator exit.
// Secrets: the CRT on the NOC's east wall (nap room), a server rack in the
// hall's east wall (Toner Launcher), and a cracked concrete panel on the
// west wall of the freight lobby.
export default defineLevel({
id: 'e1m2',
  mapLabel: 'E1M2',
  name: 'THE SERVER ROOM',
  music: 'office',
  par: 120,
  legend: {
    h: { floor: 'server-floor', ceiling: 'ceiling-light', light: 192, lightFx: 'blink' }, // emergency lights
    p: { floor: 'server-floor', ceiling: 'ceiling-tile', light: 96 }, // the dark NOC
    q: { door: 'door-metal', jamb: 'door-jamb', lock: 'remote', tag: 'noc-exit' },
    u: { door: 'crt-wall', secret: true },
    x: { door: 'server-rack', secret: true },
    y: { door: 'concrete', secret: true },
    z: { floor: 'carpet-brown', ceiling: 'ceiling-tile', light: 112, secret: true },
    v: { floor: 'server-floor', ceiling: 'ceiling-light', light: 160, secret: true },
    S: { floor: 'concrete-floor', ceiling: 'concrete', light: 120, secret: true },
  },
  thingLegend: {
    Q: { type: 'manager', skill: [3, 4, 5] },
  },
  // Coworkers (friendlies), listed by position rather than in the things grid.
  // They start in the first room, either side of the way in.
  list: [
    { type: 'gus', x: 6.5, y: 3.5 },
    { type: 'benny', x: 6.5, y: 7.5 },
  ],
  tiles: [
    '                                                                ',
    ' HHHHHHHHHTTkTTTkTTTkTTTkTTTkTTTkkkkkkkkkkkkkkkkkT              ',
    ' H-------HnnnnnnnnnnnnnnnnnnnnnTpppppppppppppppppT              ',
    ' H-------HnnnnnnnnnnnnnnnnnnnnnTpppppppppppppppppTwwwwww        ',
    ' H-------HnnnmnnnnnnmnnnnnnmnnnTpppppppppppppppppTzzzzzw        ',
    ' H-------MnnnnnnnnnnnnnnnnnnnnnTpppppppppppppppppTzzzzzw        ',
    ' H-------HnnnnnnnnnnnnnnnnnnnnnTpppppppppppppppppuzzzzzw        ',
    ' H-------Hnnnnnnnnnnnnnnnnnnnnn1pppppppppppppppppTzzzzzw        ',
    ' H-------HnnnnnnnnnnnnnnnnnnnnnTpppppppppppppppppTzzzzzw        ',
    ' HHHHHHHHHnnnnnnnnnnnnnnnnnnnnnTpppppppppppppppppTwwwwww        ',
    ' O-------TnnnmnnnnnnmnnnnnnmnnnTpppppppppppppppppT              ',
    ' O-------DnnnnnnnnnnnnnnnnnnnnnTpppppppppppppppppT              ',
    ' O-------TnnnnnnnnnnnnnnnnnnnnnTpppppppppppppppppT              ',
    ' O-------TTTTTtTTTTTDTTTtTTTTTTTTTtTTTTTqTTTtTTTTTJJJJJJJJJJJJJJ',
    ' O-------OnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnT-------------J',
    ' O-------OnnmnnnnnnnnnmnnnnnnnnnmnnnnnnnnnnnnnmnnD-------------J',
    ' O-------OnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnT--JJJJ-JJJJ--J',
    ' OOOODOOOOTTTTTnnnTTTTTTTTTTTTTTTTTTTTTTTnnnTTTTTT-------------J',
    ' I-------InnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnT-------------J',
    ' I-------InnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnT-------------J',
    ' I-------InnnZKKKKKKKZnnnZKKKKKKKZnnnZKKKKKKKZnnnT--JJJJ-JJJJ--J',
    ' J-------InhnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnhnT-------------J',
    ' I-------InnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnT-------------J',
    ' I-------InnnZKKKKKKKZnnnZKKKKKKKZnnnZKKKKKKKZnnnT-------------J',
    ' I-------InnnnnnnnnnnnnhnnnnnnnnnnnnnnnnnnnnnnnnnT--JJJJ-JJJJ--J',
    ' J-------InnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnT-------------J',
    ' I-------InnnZKKKKKKKZnnnZKKKKKKKZnnnZKKKKKKKZnnnTJJJJJJJJJJJJJJ',
    ' I-------DnnnnnnnnnnnnnnnnnnnnnnnnnhnnnnnnnnnnnnnTKKKKKK        ',
    ' I-------InnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnTvvvvvK        ',
    ' J-------InnnZKKKKKKKZnnnZKKKKKKKZnnnZKKKKKKKZnnnTvvvvvK        ',
    ' I-------InhnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnhnxvvvvvK        ',
    ' I-------InnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnTvvvvvK        ',
    ' I-------InnnZKKKKKKKZnnnZKKKKKKKZnnnZKKKKKKKZnnnTvvvvvK        ',
    ' J-------InnnnnnnnnnnnnhnnnnnnnnnnnnnnnnnnnnnnnnnTKKKKKK        ',
    ' I-------InnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnT              ',
    ' I-------InnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnT              ',
    ' I-------InnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnT              ',
    ' IIIIIIIIITTTTTTTTTTTTTTTTTTT2TTTTTTTTTTTTTTTTTTTT              ',
    '               OOOOOOH---------------H                          ',
    '               OSSSSSH---------------H                          ',
    '               OSSSSSy---------------H                          ',
    '               OSSSSSH---------------H                          ',
    '               OOOOOOH---------------H                          ',
    '                     H---------------H                          ',
    '                     HHHHHHHHLHHHHHHHH                          ',
    '                         EeeeeeeeE                              ',
    '                         EeeeeeeeE                              ',
    '                         EeeeeeeeE                              ',
    '                         EeeeeeeeE                              ',
    '                         EeeeeeeeE                              ',
    '                         EEEEXEEEE                              ',
  ],
  things: [
    '',
    '',
    '  Y    k  F                   W',
    '                            i    m      &      y',
    '                i                             c    p',
    '   >           h  h                HHHH   HHHH',
    '                          m                         O',
    '            , HHHHHH ,                  m       ;',
    '        Y                                            z',
    '                        i          HHHH   HHHH',
    '',
    '   P   i    !         s           i         %  m',
    '           =                  F ;',
    '    3   t',
    '  L                                           m               T',
    '  L   iP         ,         ,  m                        o',
    '   &                                  !',
    '',
    '                                                  p    m',
    '       o  J       i    c           d          m J            o',
    '    i',
    '',
    '                             i                       o  &   m',
    '  T',
    '      m    s                       ;',
    '                             a             i       i      o   S',
    '',
    '            m          d           4           s',
    '     c                       @                     n',
    '',
    '  o                     m                           5',
    '       i        i',
    '                                                     n',
    '   m       ;                       c           ;',
    '                              i         i',
    '    b       !                               m',
    '        d J            S                        J',
    '',
    '                      Y             Y',
    '                 S      i         i',
    '                  B',
    '                   a         Q     d',
    '                          !      @',
    '                      Y             Y',
    '',
    '',
    '',
    '',
    '                             s',
  ],
triggers: [
    {
      on: 'pickup',
      thing: 'badge-yellow',
      do: [
        { action: 'openDoors', tag: 'noc-exit' },
        { action: 'message', text: 'A DOOR UNLOCKS SOMEWHERE BELOW.' },
      ],
    },
  ],
});
