import { defineLevel } from '../../engine/defs.js';

// E1M3: SUB-BASEMENT. The freight elevator only goes down. Loading dock,
// parking garage, boiler room, and under it all, the drains.
//
// Route: loading dock -> parking garage -> security office (yellow badge)
// -> yellow door into the boiler room (Toner Launcher, red badge behind the
// boilers) -> maintenance tunnels -> red door -> the sewer grate. Step on the
// grate to climb down.
// Secrets: a roll-up door on the dock's north wall (outdoor loading bay),
// a cabinet-wall panel at the far end of the archives, and a pipe panel on
// the boiler room's south wall.
export default defineLevel({
id: 'e1m3',
  mapLabel: 'E1M3',
  name: 'SUB-BASEMENT',
  music: 'basement',
  sky: 'sky-city',
  par: 150,
  legend: {
    a: { base: '-', light: 192 }, // under a working fluorescent tube
    h: { base: '-', light: 176, lightFx: 'flicker' },
    p: { base: '-', light: 120 }, // the dark garage and tunnels
    q: { floor: 'metal-grate', ceiling: 'concrete-dark', light: 200, lightFx: 'fire', damage: 3 }, // scorching grates
    x: { floor: 'metal-grate', ceiling: 'sewer-brick', light: 160, exit: true }, // the way down
    v: { door: 'rust-panel', secret: true },
    u: { door: 'pipes', secret: true },
    y: { door: 'brick-dirty', secret: true },
    z: { floor: 'concrete-floor', ceiling: 'sky', light: 168, secret: true },
  },
  thingLegend: {
    E: { type: 'golem', skill: [3, 4, 5] },
  },
  // Coworkers (friendlies), listed by position rather than in the things grid.
  list: [
    { type: 'terry', x: 30.5, y: 25.5 },
    { type: 'dale', x: 36.5, y: 45.5 },
  ],
  tiles: [
    '            OOOOOOOOOOOOOOOOO                                   ',
    '            OzzzzzzzzzzzzzzzO                                   ',
    '            OzzzzzzzzzzzzzzzO                                   ',
    '            OzzzzzzzzzzzzzzzO                                   ',
    '            OzzzzzzzzzzzzzzzO                                   ',
    '            OzzzzzzzzzzzzzzzO                                   ',
    '       OOOJOOOJOOOJOvOOOJOOOJOOJOOjjkkkkkkkkkjjj                ',
    '       O-------------------------O-------------j                ',
    '       O-------------------------O-------------j                ',
    ' EEEEEEE---a--------a--------a---O---a-----a---j                ',
    ' EeeeeeE-------------------------O-------------j                ',
    ' EeeeeeE------HH--------HH-------O-------------j                ',
    ' EeeeeeL------HH--------HH-------O-------------j                ',
    ' EeeeeeE-------------------------O------a------j                ',
    ' EeeeeeE-------------------------O-------------j                ',
    ' EEEEEEE------------h------------O-------------j                ',
    '       O-------------------------OjjjjjjDjjjjjjjIIIIIIIIIIIIIIII',
    '       O---a-----------------a---O     j-j     I---------------I',
    '       O-------------------------O     j-j     I---------------I',
    '       O-------------------------O     j-j     I--qqqq--qqqq---I',
    'jjjjjjjOOOOOOOOOOO-----OOOOOOOOOOOOOOOOjpjOOOOOO--qUUq--qUUq---I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO--qUUq--qUUq---I',
    'jppppppOppppppppppppppppppppppppppppppppppphpppO--qqqq--qqqq---I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO---------------I',
    'jppppppOpppHHpppppOOpppppHHpppppOOpppppHHppppppO---------------I',
    'jppppppOpppHHpppppOOpppppHHpppppOOpppppHHppppppO-------a-------I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppJ---------------I',
    'jppppppDppppppphppppppppppppphpppppppppppppppppO---------------I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO---------------I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO---------------I',
    'jppppppOpppHHpppppOOpppppHHpppppOOpppppHHppppppO---------------I',
    'jppppppOpppHHpppppOOpppppHHpppppOOpppppHHpppppp2--a---------a--J',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO---------------I',
    'jppppppOpppppppppppppphppppppppppppphppppppppppO---------------I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO---------------I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO-------a-------I',
    'jppppppOpppHHpppppOOpppppHHpppppOOpppppHHppppppJ---------------I',
    'jppppppDpppHHpppppOOpppppHHpppppOOpppppHHppppppO---------------I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO--qqqq--qqqq---I',
    'jppppppOppppppphpppppppppppppppppppppppppppppppO--qUUq--qUUq---I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO--qUUq--qUUq---I',
    'jppppppOpppppppppppppppppppppppppppppppppppppppO--qqqq--qqqq---I',
    'jppppppOOOOOOOOOOOOOOOOOOOOMOOOOOOOOOOOOOOOOOOOO---------------I',
    'jppppppj      IpppppppppppppppppppppppppI      I---------------I',
    'jppppppj      IphppppppppppppppppppppphpI      I---------------I',
    'jppppppj      IpppppppppppppppppppppppppI      I---------------I',
    'jppppppj      IpppppppppppppppppppppppppI      IIIIIIIIuIIIIIIII',
    'jppppppj      IppppJJJJJJJJDJJJJJJJJppppIGGgGGGgGGG IzzzzzI     ',
    'jppppppj      IppppJ---------------JppppIsssssssssG IzzzzzI     ',
    'jppppppj      IppppJ---------------JppppIsssssssssG IzzzzzI     ',
    'jjjyjjjj      IppppJ----~~~~~~~----JppppIsssssssssG IzzzzzI     ',
    'jzzzzzzj      IppppJ----~~~~~~~----Jpppp3ssssxxsssG IIIIIII     ',
    'jzzzzzzj      IppppJ----~~~~~~~----JppppIssssxxsssG             ',
    'jzzzzzzj      IppppJ---------------JppppIsssssssssG             ',
    'jzzzzzzj      IppppJ---------------JppppIsssssssssG             ',
    'jjjjjjjj      IppppJJJJJJJJDJJJJJJJJppppIsssssssssG             ',
    '              IpppppppppppppppppppppppppIGGgGGGgGGG             ',
    '              IpppppppppppppppppppppppppI                       ',
    '              IphppppppppppppppppppppphpI                       ',
    '              IpppppppppppppppppppppppppI                       ',
    '              IIIIIIIIIIIIIIIIIIIIIIIIIII                       ',
  ],
  things: [
    '',
    '              P',
    '                    U',
    '                  B   N',
    '',
    '                          P',
    '',
    '        ;                       d',
    '         P  s    C        o    I   i         y',
    '          r            m               h h',
    '                                      HHHHH',
    '                              i',
    '   >                U',
    '                            s',
    '                i                   M       i',
    '             o             C      S           L',
    '                  T',
    '                          i                           o    E',
    '            !        @P        P        s        m           R',
    '         I         r            r',
    '',
    ' t',
    '    i        i  ,                 !',
    '  L  L                      m                @',
    '  L',
    '                                            d        p    N',
    '    m     r           c            i                         m',
    '',
    ' r            C      i               s           c',
    '  L                           3           m',
    '  L  L                                                 5',
    '   d                       r                     n   r       n',
    '      r         $',
    '  L  L   m                              ,  $',
    '  L                           i',
    '                    s                 r         i',
    '   i                                                        c',
    '                 m         a       C',
    '      t                I                    i',
    '  L      T                          c',
    '  L  L      !           i        ,                            o',
    '                   r                         I',
    '   r',
    '      &         m                                 m    M',
    '  L  L                   i s                                  r',
    '  L                                    $        o',
    '                r',
    '     i',
    ' r                  o          p      r                A',
    '                     m          c         r     a     , ,',
    '                 r',
    '',
    '  g  e',
    '                      N          m   r',
    '   S                              o       m     r',
    '               $',
    '',
    '                                 r    m',
    '                      r    s',
    '                             i',
  ],
triggers: [
    { on: 'pickup', thing: 'badge-red', do: [{ action: 'message', text: 'THE BOILERS ROAR. SOMETHING UNDER THE FLOOR ROARS BACK.' }] },
  ],
});
