import { defineLevel } from '../../engine/defs.js';

// E1M4: THE SEWERS. Under the building the drains run on forever, and the
// rats have opinions about visitors.
//
// Route: along the channel -> flooded cistern (blue badge on the island;
// grab the waders on the ledge first) -> blue door into the control room
// (yellow badge, Toner Launcher) -> yellow door into the pumping station
// -> the tunnel where the brick turns to flesh. Use the eye to go down.
// Secrets: a slimy panel on the storage room's east wall, a brick in the
// cistern's south wall, and a soft spot in the rat nest's bottom wall
// (the B.F.C. 9000).
export default defineLevel({
id: 'e1m4',
  mapLabel: 'E1M4',
  name: 'THE SEWERS',
  music: 'sewer',
  par: 180,
  fog: 0.3,
  legend: {
    a: { floor: 'sewer-floor', ceiling: 'metal-grate', light: 208 }, // light falling through a street grate
    h: { base: '-', light: 176, lightFx: 'flicker' },
    s: { floor: 'sewer-floor', ceiling: 'sewer-brick', light: 152 }, // brighter than the shared walkway
    '~': { floor: 'sewage', ceiling: 'sewer-brick', light: 160, damage: 6 },
    p: { base: 's', light: 112 }, // the rat nest
    x: { floor: 'dirt', ceiling: 'flesh-trash', light: 136, lightFx: 'glow' },
    0: { wall: 'flesh-eye', use: 'exit' },
    u: { door: 'sewer-brick-slime', secret: true },
    v: { door: 'sewer-brick-slime', secret: true },
    y: { door: 'trash-wall', secret: true },
    z: { floor: 'sewer-floor', ceiling: 'sewer-brick', light: 144, secret: true },
  },
  thingLegend: {
    E: { type: 'golem', skill: [3, 4, 5] },
  },
  tiles: [
    '                                                                ',
    ' GGGGGGGGG            TTTkTkTkTkTkTkTkTkTTT jjjjjjjjjjjjjGGGGGG ',
    ' GsssasssG            TnnnnnnnnnnnnnnnnnnnT j-----------jzzzzzG ',
    ' Gsssssssg            TnnnnnnnnnnnnnnnnnnnT j-----------jzzzzzG ',
    ' gsssssssG            TnnnnnnnnnnnnnnnnnnnT j-----------jzzzzzG ',
    ' GsssssssG            TnnnnnnnnnnnnnnnnnnnT j-----------vzzzzzG ',
    ' GsssssssG            TnnnnnnnnnnnnnnnnnnnT j-----------jzzzzzG ',
    ' GsssssssG            TnnnnnnnnnnnnnnnnnnnT j-----------jzzzzzG ',
    ' GsssssssG            TnnnnnnnnnnnnnnnnnnnT j-----------jzzzzzG ',
    ' GGGsssGGGGGGGGGGGgGGGGGGGgGGGGG1GGGgGGGGGGGGGgGGGRGGGGGGGgGGGG ',
    ' GssssssssssssssssssssgsssssssssssssssssgsssssssssssssssssssssG ',
    ' GssssssassssssssssssssssssassssssssssssssssasssssssssssssasssG ',
    ' GssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssG ',
    ' GssssssssssssssssssssgsssssssssssssssssgsssssssssssssssssssssG ',
    ' G~~~~~~~~~~~~ss~~~~~~~~~~~~~~~ss~~~~~~~~~~~~~~~ss~~~~~~~~~~~~G ',
    ' G~~~~~~~~~~~~ss~~~~~~~~~~~~~~~ss~~~~~~~~~~~~~~~ss~~~~~~~~~~~~G ',
    ' G~~~~~~~~~~~~ss~~~~~~~~~~~~~~~ss~~~~~~~~~~~~~~~ss~~~~~~~~~~~~G ',
    ' GssssssssssssssssssssgsssssssssssssssssgsssssssssssssssssssssG ',
    ' GssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssG ',
    ' GssssssssssasssssssssssssssssssssssasssssssssssssssssasssssssG ',
    ' GssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssG ',
    ' GssssssssssssssssssssgsssssssssssssssssgsssssssssssssssssssssG ',
    ' GGGGGgGsssGGGGGGGgGGGGGGGgGGGGGGssGgGGGGGGGGGgGGGGG2GGGGGgGGGG ',
    ' GsssssssssssssssssssssssGpppppppppppppppppF------------------J ',
    ' GsssssssssssssssssssssssGpppppppppppppppppF------------------J ',
    ' G~~~~~~~~~~~~~~~~~~~~~~~GpppppppppppppppppF--------h---------J ',
    ' G~~~~~~~~~~~~~~~~~~~~~~~GpppppppppppppppppF------------------J ',
    ' G~~~~~~~ss~~~~~~~~~~~~~~GfffffffffffffffppF---II------II-----J ',
    ' G~~~~~~~ss~~~~~~~~~~~~~~GpppppppppppppppppF---II------II-----J ',
    ' G~~~~~~~~~~~~~~~~~~~~~~~GpppppppppppppppppF---II------II-----J ',
    ' G~~~~~~~~~~ss~~~~~~~~~~~GpppppppppppppppppF------------------J ',
    ' G~~~gg~~~~~ss~~~~~gg~~~~GpppppppppppppppppF------------------J ',
    ' G~~~gg~~~~~~~~~~~~gg~~~~GppFFFFFFFFFFFFFFFF-h------h-------h-J ',
    ' G~~~~~~~~~~~~~ss~~~~~~~~GpppppppppppppppppF------------------J ',
    ' G~~~~~~~~~~~~~ss~~~~~~~~GpppppppppppppppppF------------------J ',
    ' G~~~~~~~~sssssss~~~~~~~~GpppppppppppppppppF------------------J ',
    ' G~~~~~~~~sssssss~~~~~~~~GpppppppppppppppppF---II------II-----J ',
    ' G~~~~~~~~sssssss~~~~~~~~GFFFFFFFFFFFFFFFppF---II------II-----J ',
    ' G~~~~~~~~sssssss~~~~~~~~GpppppppppppppppppF---II------II-----J ',
    ' G~~~~~~~~sssssss~~~~~~~~GpppppppppppppppppF------------------J ',
    ' G~~~~~~~~sssssss~~~~~~~~GpppppppppppppppppF--------h---------J ',
    ' G~~~~~~~~sssssss~~~~~~~~GpppppppppppppppppF------------------J ',
    ' G~~~~~~~~~~~~~~~~~~~~~~~GppfffffffffffffffF------------------J ',
    ' G~~~~~~~~~~~~~~~~~~~~~~~GpppppppppppppppppF------------------J ',
    ' G~~~gg~~~~~~~~~~~~gg~~~~GpppppppppppppppppFJJJJJJJJJRJJJJJJJJJ ',
    ' G~~~gg~~~~~~~~~~~~gg~~~~GpppppppppppppppppF  fxxxxxxxxxxxxxf   ',
    ' G~~~~~~~~~~~~~~~~~~~~~~~GpppppppppppppppppF  fxxxxxxxxxxxxxf   ',
    ' G~~~~~~~~~~~~~~~~~~~~~~~GFFFFFFFFFFFFFFFppF  fxxxxxxxxxxxxxf   ',
    ' G~~~~~~~~~~~~~~~~~~~~~~~GpppppppppppppppppF  Yxxxxxxxxxxxxxb   ',
    ' G~~~~~~~~~~~~~~~~~~~~~~~GpppppppppppppppppF  fxxxxxxxxxxxxxf   ',
    ' GGGGGGGGGGGGuGGGGGGGGGGGGpppppppppppppppppF  fxxxxxxxxxxxxxf   ',
    '         GzzzzzzzG       FpppppppppppppppppF  fxxxxxxxxxxxxxf   ',
    '         GzzzzzzzG       FFFFFyFFFFFFFFFFFFF  Yxxxxxxxxxxxxxb   ',
    '         GzzzzzzzG       fzzzzzzzzzf          fxxxxxxxxxxxxxf   ',
    '         GzzzzzzzG       fzzzzzzzzzf          fxxxxxxxxxxxxxf   ',
    '         GzzzzzzzG       fzzzzzzzzzf          fxxxxxxxxxxxxxf   ',
    '         GGGGGGGGG       fzzzzzzzzzf          Yxxxxxxxxxxxxxb   ',
    '                         fzzzzzzzzzf          fxxxxxxxxxxxxxf   ',
    '                         fffffffffff          fxxxxxxxxxxxxxf   ',
    '                                              fxxxxxxxxxxxxxf   ',
    '                                              fffffff0fffffff   ',
  ],
  things: [
    '',
    '',
    '  x                                              T     S',
    '     v                  m       M       y     o       o   N',
    '                            HHH   HHH             4',
    '        t                                       m          O',
    '                                5                   m',
    '   3   x                 &             m       o       c    q',
    '                        N                p   S       o',
    '',
    '',
    '            r       $            T   r    @                  c',
    '   P            s        r  i      m         s      r    $  n',
    '',
    '',
    '',
    '',
    '',
    '',
    '          i      r      G     d              r          m',
    '   ,               m         r         P   $      i        r P',
    '',
    '',
    '   w            d     m                  r                   N',
    '      a                s    r      s      P  m',
    '                               r    r                a      m',
    '                                                 o',
    '',
    '                                                    c',
    '                              r   $',
    '                                      r  G        i      o',
    '                          P',
    '',
    '                                i           N',
    '                           r  s        r           M  i',
    '             N$                    r',
    '           r    r                        d',
    '',
    '             b      m     `                         c',
    '                               $        r        o',
    '          $    r             r    p       P',
    '            G                                             % &',
    '                                             m',
    '                                     i                       S',
    '                                 r',
    '                           G             r     U           U',
    '                            d                   r',
    '    m                                                d    r',
    '',
    '                           r          $              E',
    '                                    r     T     x',
    '                          P',
    '                                                 G       G',
    '             A',
    '           q   q           Q     q',
    '                              6                           x',
    '                            x    q',
    '                                                  r',
    '                                                    x   r',
    '                                               U           U',
  ],
triggers: [
    { on: 'start', do: [{ action: 'message', text: 'THE SMELL HITS LIKE A PERFORMANCE REVIEW.' }] },
    { on: 'pickup', thing: 'pickup-bfc', do: [{ action: 'message', text: 'THE B.F.C. 9000. DECAF IS FOR THE WEAK.' }] },
  ],
});
